DROP TABLE IF EXISTS ambiances_sounds CASCADE;
DROP TABLE IF EXISTS ambiances CASCADE;
DROP TABLE IF EXISTS sounds CASCADE;
DROP TABLE IF EXISTS user_has_favorite_sounds CASCADE;
DROP TABLE IF EXISTS user_has_favorite_ambiances CASCADE;
DROP TYPE IF EXISTS category;
DROP TYPE IF EXISTS theme;